# Site settings
title: Keto's blog
email: jsw5203@gmail.com
description: >- 
  Pwnable Blog
baseurl: "" # Set to "/blog" if you publish under a subpath
url: "https://keto0422.github.io" # Site URL
lang: "en-US"
timezone: "Asia/Seoul"



# Social media
twitter_username: 
github_username: 

# Blog settings
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
theme: minima
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
# Excluded files/folders
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - bin/

# Default layout and values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Keto"

# Search is implemented manually
# Keep both search.json and search.md
